/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

export interface VerdictResult {
  kind: string
  evaluator?: string
  reason?: string
  code?: string
  tokenId?: string
  isPermit: boolean
  isRefuse: boolean
  isInvalidate: boolean
  /**
   * Full PermitToken (with optional signature) when verdict is Permit.
   * `null` for Refuse / Invalidate.
   */
  permitToken?: PermitTokenView
  /** Convenience: signature bytes (or null) — same as `permit_token.signature`. */
  signature?: Buffer
}
/**
 * JS-visible view of a PermitToken. Use the standalone `PermitToken` class
 * when you need to construct one from received-over-the-wire fields (for
 * verification on a downstream service).
 */
export interface PermitTokenView {
  tokenId: string
  evaluationId: string
  /** Issued-at unix-epoch seconds. */
  issuedAt: number
  /** Expires-at unix-epoch seconds. */
  expiresAt: number
  actionName: string
  signature?: Buffer
}
export interface ActionContextInput {
  principalId: string
  principalKind: string
  actionName: string
  roles?: Array<string>
  resource?: string
  params?: Record<string, number>
  ip?: string
  sessionId?: string
  /**
   * Current geographic location (→ `EnvContext.geo`). Set this plus
   * `originGeo` and a tolerant-mode `GeoLocationDrift` evaluator to
   * downgrade same-country IP hops from Violation to Warning.
   */
  currentGeo?: GeoLocationInput
  /**
   * Geographic location captured at session start
   * (→ `SessionState.origin_geo`). Needed alongside `currentGeo` for
   * tolerant-mode `GeoLocationDrift`.
   */
  originGeo?: GeoLocationInput
  /**
   * Explicit session-origin IP. When set, overrides the `ip`-derived
   * default (`session.origin_ip = env.ip`) — lets callers model
   * "session started from X, request from Y" for strict/tolerant
   * `GeoLocationDrift`.
   */
  originIp?: string
  /**
   * Current device fingerprint (→ `EnvContext.device`). Combined
   * with `originDevice`, feeds `DeviceDrift`.
   */
  device?: DeviceFingerprintInput
  /**
   * Session-origin device fingerprint (→ `SessionState.origin_device`).
   * `DeviceDrift` fires when both sides are set and the hashes differ.
   */
  originDevice?: DeviceFingerprintInput
  /**
   * Unix-epoch seconds; synthesizes `SessionState.started_at`. Lets
   * scenarios exercise `SessionAgeDrift` without waiting hours.
   */
  sessionStartedAt?: number
  /**
   * Synthesized `SessionState.action_count`. Combined with a
   * synthesized `session_started_at`, feeds `BehaviorDrift`'s
   * actions-per-minute calculation.
   */
  actionCount?: number
}
/**
 * Plain-object view of `kavach_core::GeoLocation`. `countryCode` is
 * required; `latitude` + `longitude` unlock Haversine distance (needed
 * for tolerant-mode drift). `region` / `city` are free-text annotations.
 */
export interface GeoLocationInput {
  countryCode: string
  region?: string
  city?: string
  latitude?: number
  longitude?: number
}
/**
 * Plain-object view of `kavach_core::DeviceFingerprint`. `hash` is
 * required; `description` is free-text for drift violation messages.
 */
export interface DeviceFingerprintInput {
  hash: string
  description?: string
}
export interface InvariantInput {
  name: string
  field: string
  maxValue: number
}
/**
 * Fields needed to (re)construct a PermitToken on the verifier side.
 * Matches what `PermitToken` uses internally; pass this when calling
 * `signer.verifyToken(...)` from JS.
 */
export interface PermitTokenInput {
  tokenId: string
  evaluationId: string
  /** Unix-epoch seconds. */
  issuedAt: number
  /** Unix-epoch seconds. */
  expiresAt: number
  actionName: string
}
/** JS-visible public-key bundle. Plain object so JS can pluck fields directly. */
export interface PublicKeyBundleView {
  id: string
  mlDsaVerifyingKey: Buffer
  mlKemEncapsulationKey: Buffer
  ed25519VerifyingKey: Buffer
  x25519PublicKey: Buffer
  /** Created-at unix-epoch seconds. */
  createdAt: number
  /** Expires-at unix-epoch seconds (null if no expiry). */
  expiresAt?: number
}
/** Optional fields for `AuditEntry.new`. */
export interface AuditEntryOptions {
  resource?: string
  decidedBy?: string
  ip?: string
  evaluationId?: string
  sessionId?: string
}
/**
 * JS-visible view of a [`core::InvalidationScope`]. Passed as the
 * sole argument to the callback registered via
 * `spawnInvalidationListener`. `targetKind` is `"session"`,
 * `"principal"`, or `"role"`; `targetId` is the matching id (UUID
 * string for session, principal id for principal, role name for role).
 */
export interface InvalidationScopeView {
  targetKind: string
  targetId: string
  reason: string
  evaluator: string
}
/**
 * Spawn a listener that calls `callback(scope)` for every
 * invalidation published on `broadcaster`.
 *
 * `callback` is any JS function taking a single
 * `InvalidationScopeView` argument. The callback runs on the Node
 * event loop (ThreadsafeFunction); exceptions thrown inside the
 * callback do NOT stop the listener — they surface through the
 * napi error strategy.
 *
 * Returns an `InvalidationListenerHandle`; call `.abort()` to stop
 * the task before the broadcaster's channel closes.
 */
export declare function spawnInvalidationListener(broadcaster: InMemoryInvalidationBroadcaster, callback: (...args: any[]) => any): InvalidationListenerHandle
/**
 * A Kavach keypair — ML-DSA-65 + ML-KEM-768 + Ed25519 + X25519.
 *
 * Holds *both* signing/decapsulation/secret keys and their public counterparts.
 * Use `publicKeys()` to extract the safe-to-share `PublicKeyBundle` and
 * share *that* with verifiers — never the keypair itself.
 */
export declare class KavachKeyPair {
  /** Generate a fresh random keypair (no expiry). */
  static generate(): KavachKeyPair
  /** Generate a fresh random keypair that expires after `seconds`. */
  static generateWithExpiry(seconds: number): KavachKeyPair
  get id(): string
  get createdAt(): number
  get expiresAt(): number | null
  /** True if this keypair has passed its expiry. */
  get isExpired(): boolean
  /** The safe-to-share half — share this with verifiers / KEM senders. */
  publicKeys(): PublicKeyBundleView
  /**
   * Sign a `PublicKeyDirectory` manifest with this keypair's ML-DSA-65
   * seed, returning the JSON bytes of a root-signed manifest.
   *
   * Load on a verifier with
   * `PublicKeyDirectory.fromSignedFile(path, rootMlDsaVerifyingKey)`,
   * where `rootMlDsaVerifyingKey` is this keypair's public
   * `mlDsaVerifyingKey`. The signing seed never crosses the FFI.
   */
  buildSignedManifest(bundles: Array<PublicKeyBundleView>): Buffer
}
/**
 * PQ token signer — wraps `kavach_pq::PqTokenSigner` and exposes
 * sign/verify across the FFI.
 *
 * Construct via `PqTokenSigner.pqOnly(...)` (ML-DSA-65 only) or
 * `PqTokenSigner.hybridFromBytes(...)` (ML-DSA-65 + Ed25519). For tests
 * and quick starts, `PqTokenSigner.generatePqOnly()` /
 * `PqTokenSigner.generateHybrid()` produce a fresh keypair internally.
 */
export declare class PqTokenSigner {
  /** Build a PQ-only (ML-DSA-65) signer from raw key bytes. */
  static pqOnly(mlDsaSigningKey: Buffer, mlDsaVerifyingKey: Buffer, keyId: string): PqTokenSigner
  /** Build a hybrid (ML-DSA-65 + Ed25519) signer from raw key bytes. */
  static hybridFromBytes(mlDsaSigningKey: Buffer, mlDsaVerifyingKey: Buffer, ed25519SigningKey: Buffer, ed25519VerifyingKey: Buffer, keyId: string): PqTokenSigner
  /**
   * Generate a fresh PQ-only signer (random ML-DSA-65 keypair).
   * Convenience for tests / quick starts. For production key management
   * you'll want to persist the keypair — use `pqOnly(...)` instead.
   */
  static generatePqOnly(keyId?: string | undefined | null): PqTokenSigner
  /** Generate a fresh hybrid signer (random ML-DSA-65 + Ed25519 keypair). */
  static generateHybrid(keyId?: string | undefined | null): PqTokenSigner
  /**
   * Build a PQ-only signer from an existing `KavachKeyPair`.
   * Forwards `kp.id` as the key_id (override with `keyId`).
   */
  static fromKeypairPqOnly(keypair: KavachKeyPair, keyId?: string | undefined | null): PqTokenSigner
  /** Build a hybrid signer from an existing `KavachKeyPair`. */
  static fromKeypairHybrid(keypair: KavachKeyPair, keyId?: string | undefined | null): PqTokenSigner
  get keyId(): string
  get isHybrid(): boolean
  /**
   * Sign a PermitToken (described by its primitive fields).
   * Returns the JSON-encoded `SignedTokenEnvelope` bytes.
   */
  sign(token: PermitTokenInput): Buffer
  /**
   * Verify `signature` against the supplied PermitToken fields.
   * Throws on any failure (tampering, wrong key, malformed envelope,
   * algorithm mismatch).
   */
  verify(token: PermitTokenInput, signature: Buffer): void
}
/**
 * A single audit-log entry. Pass these to `SignedAuditChain.append`.
 *
 * Required fields: `principalId`, `actionName`, `verdict`
 * (`"permit"` / `"refuse"` / `"invalidate"`), and `verdictDetail`.
 * All other fields default sensibly: a fresh UUID for `id` /
 * `evaluationId` / `sessionId`, and `Date.now()` for `timestamp`.
 */
export declare class AuditEntry {
  /**
   * Construct an audit entry. `verdict` must be one of
   * `"permit"`, `"refuse"`, `"invalidate"`.
   */
  static new(principalId: string, actionName: string, verdict: string, verdictDetail: string, options?: AuditEntryOptions | undefined | null): AuditEntry
  get id(): string
  get principalId(): string
  get actionName(): string
  get verdict(): string
}
/**
 * A tamper-evident PQ-signed audit log.
 *
 * Each appended entry is signed (ML-DSA-65, plus Ed25519 in hybrid mode)
 * and linked to the previous entry via a SHA-256 hash chain. Reordering,
 * inserting, deleting, mutating, or splicing across modes is detected at
 * `verify` time. The verifier's mode must match the chain's mode —
 * `verify` and `verifyJsonl` refuse to silently accept a hybrid chain
 * under a PQ-only verifier (and vice versa), closing the
 * signature-downgrade surface.
 */
export declare class SignedAuditChain {
  /**
   * Construct a chain backed by the supplied keypair. `hybrid` defaults
   * to true (ML-DSA-65 + Ed25519). The verifier mode at `verify` time
   * must match.
   */
  constructor(keypair: KavachKeyPair, hybrid?: boolean | undefined | null)
  /** Append an audit entry. Returns the new chain length. */
  append(entry: AuditEntry): number
  get length(): number
  get isEmpty(): boolean
  get headHash(): string
  get isHybrid(): boolean
  /**
   * Verify all entries in-place using the supplied public-key bundle.
   * Throws on any tamper / signature mismatch / chain break / verifier
   * mode mismatch.
   */
  verify(publicKeys: PublicKeyBundleView): void
  /**
   * Export the chain as newline-delimited JSON bytes (`.jsonl`).
   * One `SignedAuditEntry` per line. Trailing newline included.
   */
  exportJsonl(): Buffer
  /**
   * Verify a previously-exported JSONL chain against the supplied
   * public-key bundle. Returns the number of verified entries.
   *
   * The chain's mode is inferred from the blob. When `hybrid` is passed
   * explicitly it acts as a strict assertion: an expectation mismatch
   * throws *before* any crypto is attempted, preventing a caller from
   * silently verifying a hybrid chain with a PQ-only verifier (or vice
   * versa). Omit `hybrid` to trust the blob.
   *
   * Throws on tamper / signature mismatch / chain break / mode mismatch.
   */
  static verifyJsonl(data: Buffer, publicKeys: PublicKeyBundleView, hybrid?: boolean | undefined | null): number
}
export declare class KavachGate {
  /**
   * Create a new Kavach gate from TOML policy configuration.
   *
   * All evaluation logic runs in compiled Rust.
   * When a `tokenSigner` is supplied, every Permit verdict carries a
   * signed envelope on `verdict.signature` / `verdict.permitToken.signature`.
   * Sign failures fail closed (Refuse).
   *
   * `geoDriftMaxKm`: tolerance (km) for `GeoLocationDrift`. When unset,
   * any mid-session IP change is a Violation. When set, an IP change
   * within this distance downgrades to a Warning — requires both
   * `currentGeo` and `originGeo` to carry latitude/longitude. Missing
   * geo with a threshold set fails closed.
   */
  constructor(policyToml: string, invariants?: Array<InvariantInput> | undefined | null, observeOnly?: boolean | undefined | null, maxSessionActions?: number | undefined | null, enableDrift?: boolean | undefined | null, tokenSigner?: PqTokenSigner | undefined | null, geoDriftMaxKm?: number | undefined | null, broadcaster?: InMemoryInvalidationBroadcaster | undefined | null)
  /**
   * Hot-reload the policy set from a fresh TOML string.
   *
   * Parse errors throw and the previous good set stays in place — never
   * wipe a running engine on a bad reload. An empty TOML is intentionally
   * valid (= default-deny everything; useful as a kill-switch).
   */
  reload(policyToml: string): void
  /**
   * Evaluate an action context. Returns a VerdictResult.
   *
   * Crosses into Rust for all evaluation: policy, drift, invariants.
   * When the gate was configured with `observeOnly: true`, the full
   * evaluator chain still runs and real Refuse/Invalidate verdicts
   * still reach the audit sink and the broadcaster — but the
   * caller-facing verdict is always Permit. Operators get full
   * visibility of what the gate *would* do without production
   * traffic being refused during a rollout.
   */
  evaluate(ctx: ActionContextInput): VerdictResult
  /** Number of evaluators in the gate chain. */
  get evaluatorCount(): number
}
/**
 * A hybrid-encrypted, PQ-signed channel between two Kavach services.
 *
 * Each side constructs a channel from their own `KavachKeyPair` (secret
 * material — never share) and the remote party's `PublicKeyBundle`
 * (safe to share). Sealed payloads are opaque `Buffer`s carrying the
 * full envelope; store or transmit them anywhere.
 *
 * Three flows:
 * - `sendSigned(data, contextId, correlationId)` / `receiveSigned(sealed,
 *   expectedContextId)` — sign + encrypt, with replay protection and
 *   context binding. Throws on tamper, wrong recipient, replay, or
 *   context mismatch.
 * - `sendData(data)` / `receiveData(sealed)` — encryption only, no
 *   signing.
 * - `localKeyId` / `remoteKeyId` getters for diagnostics.
 */
export declare class SecureChannel {
  /**
   * Construct a channel from this side's full keypair and the remote
   * party's public-key bundle.
   */
  constructor(localKeypair: KavachKeyPair, remotePublicKeys: PublicKeyBundleView)
  get localKeyId(): string
  get remoteKeyId(): string
  /**
   * Sign + encrypt `data`, binding it to `contextId` and
   * `correlationId`. Returns opaque sealed bytes — pass them to the
   * remote side's `receiveSigned`.
   */
  sendSigned(data: Buffer, contextId: string, correlationId: string): Buffer
  /**
   * Decrypt + signature/replay/context-verify. Throws on any failure
   * (decrypt, tamper, replay, wrong context, wrong recipient).
   */
  receiveSigned(sealed: Buffer, expectedContextId: string): Buffer
  /**
   * Encrypt `data` with no signing and no replay tracking. Use
   * `sendSigned` when you need integrity + authenticity + replay
   * protection.
   */
  sendData(data: Buffer): Buffer
  /** Decrypt a sealed payload. Throws on any failure. */
  receiveData(sealed: Buffer): Buffer
}
/**
 * Public-key distribution surface for downstream verifiers.
 *
 * Three backings:
 * - `PublicKeyDirectory.inMemory(bundles)` — programmatic store,
 *   mutable via `insert` / `remove`.
 * - `PublicKeyDirectory.fromFile(path)` — unsigned JSON array on
 *   disk. Safe only when the file is local to the verifier.
 * - `PublicKeyDirectory.fromSignedFile(path, rootMlDsaVerifyingKey)`
 *   — root-signed manifest. Any file whose ML-DSA-65 signature
 *   doesn't verify against `rootMlDsaVerifyingKey` is rejected at
 *   load time. Use this for cross-host trust.
 *
 * `fetch(keyId)` throws on any failure (NotFound /
 * BackendUnavailable / RootSignatureInvalid / Corrupt) — fail-closed
 * so unverifiable tokens can't be silently accepted.
 */
export declare class PublicKeyDirectory {
  /** Build an in-memory directory, optionally pre-populated. */
  static inMemory(bundles?: Array<PublicKeyBundleView> | undefined | null): PublicKeyDirectory
  /** Load an unsigned bundle array from disk. */
  static fromFile(path: string): PublicKeyDirectory
  /**
   * Load a root-signed manifest; any manifest whose signature
   * does not verify against `rootMlDsaVerifyingKey` is rejected.
   */
  static fromSignedFile(path: string, rootMlDsaVerifyingKey: Buffer): PublicKeyDirectory
  /** Fetch a bundle by `keyId`. Throws on any failure. */
  fetch(keyId: string): PublicKeyBundleView
  /** Insert (or overwrite) a bundle. Throws on file-backed directories. */
  insert(bundle: PublicKeyBundleView): void
  /** Remove a bundle by id. Throws on file-backed directories. */
  remove(keyId: string): boolean
  /**
   * Re-read the underlying file. No-op for in-memory directories.
   * Parse / signature errors throw; the previous cache is preserved.
   */
  reload(): void
  get length(): number
  get isEmpty(): boolean
  /**
   * Build the JSON bytes of an unsigned bundle array suitable for
   * `fromFile(...)`.
   */
  static buildUnsignedManifest(bundles: Array<PublicKeyBundleView>): Buffer
  /**
   * Build the JSON bytes of a root-signed manifest suitable for
   * `fromSignedFile(...)`. `mlDsaSigningKey` is the 32-byte
   * ML-DSA-65 seed of the root authority.
   */
  static buildSignedManifest(bundles: Array<PublicKeyBundleView>, mlDsaSigningKey: Buffer): Buffer
}
/**
 * Verifies `PermitToken` signatures by looking up the matching
 * `PublicKeyBundle` in a `PublicKeyDirectory` via the envelope's
 * `key_id`. Fail-closed — any failure throws.
 */
export declare class DirectoryTokenVerifier {
  /**
   * `hybrid` defaults to true (ML-DSA-65 + Ed25519 required).
   * Setting it to false makes this a PQ-only verifier that
   * rejects hybrid envelopes.
   */
  constructor(directory: PublicKeyDirectory, hybrid?: boolean | undefined | null)
  /**
   * Verify `signature` against the supplied PermitToken fields.
   * Throws on any failure (envelope parse, algorithm mismatch,
   * directory miss, signature invalid, expired bundle).
   *
   * `enforceExpiry` (default `true`): reject verification if the
   * resolved bundle's `expires_at` is in the past. This is the
   * correct-by-default posture for an authorization gate — a
   * rotated-out keypair MUST NOT authorise new actions even if
   * its signature is still cryptographically valid. Pass
   * `enforceExpiry: false` for historical forensic verification
   * (re-checking an archived audit trail against a bundle that
   * has since expired).
   */
  verify(token: PermitTokenInput, signature: Buffer, enforceExpiry?: boolean | undefined | null): void
}
/**
 * Process-local invalidation broadcaster — default backend when no
 * Redis broadcaster is configured.
 *
 * Subscribers created via `spawnInvalidationListener` receive every
 * `publish` that arrives *after* the subscription. Useful for
 * single-node deployments that still want a uniform code path with
 * the distributed broadcaster, and for smoke tests that exercise
 * the broadcaster contract without standing up Redis.
 */
export declare class InMemoryInvalidationBroadcaster {
  constructor()
  /**
   * Manually publish an invalidation. Real callers get this for
   * free through `Gate.evaluate()` when an evaluator returns
   * `Invalidate`; this method is here for tests / scenarios that
   * want to exercise the subscribe path without routing a
   * synthetic Invalidate through the gate.
   *
   * `targetKind` must be `"session"`, `"principal"`, or `"role"`.
   * For `"session"`, `targetId` MUST be a valid UUID string.
   */
  publish(targetKind: string, targetId: string, reason: string, evaluator?: string | undefined | null): void
  /** Live subscriber count (observability / tests). */
  get subscriberCount(): number
}
/**
 * Opaque handle for a running listener task spawned by
 * `spawnInvalidationListener`. Integrator owns the lifecycle —
 * the task exits on its own when the broadcaster's channel closes;
 * call `abort()` to stop it sooner.
 */
export declare class InvalidationListenerHandle {
  /** Stop the listener. Idempotent — calling twice is a no-op. */
  abort(): void
  /** True if the listener task has finished. */
  get isFinished(): boolean
}
